services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: tigo-elasticsearch
    environment:
      - node.name=tigo-es-node
      - cluster.name=tigo-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - tigo-network

  kibana:
    image: kibana:8.11.0
    container_name: tigo-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - tigo-network

volumes:
  elasticsearch_data:

networks:
  tigo-network:
    driver: bridge